name: Next.js Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIrons/gh-pages-deploy-action@v1
        with:
          BRANCH: gh-pages # The branch to deploy to
          FOLDER: out # The folder to deploy
          TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token
